import { getDigestList } from '@/lib/digests'
import { DigestCard } from '@/components/DigestCard'

export const metadata = {
  title: 'AI Developer Digest — Dev Hub',
  description: 'Daily AI developer news: model releases, API changes, research, tooling, and trends. Filtered for real developer signal.',
}

export default function DigestIndexPage() {
  const digests = getDigestList()

  return (
    <main style={{ background: '#030712', minHeight: 'calc(100vh - 48px)', padding: '48px 24px' }}>
      <div style={{ maxWidth: 760, margin: '0 auto' }}>

        <div style={{ marginBottom: 48 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 16 }}>
            <span style={{ fontSize: 28 }}>📡</span>
            <h1 style={{ fontSize: 28, fontWeight: 700, color: '#F1F5F9', margin: 0 }}>
              AI Developer Digest
            </h1>
          </div>
          <p style={{ color: '#64748B', fontSize: 15, margin: 0, lineHeight: 1.6 }}>
            Daily signal for developers — model releases, API changes, research, tooling updates,
            and emerging trends. Filtered from 30+ sources. Zero fluff.
          </p>
        </div>

        {digests.length === 0 ? (
          <div style={{
            border: '1px solid rgba(255,255,255,0.07)',
            borderRadius: 12,
            padding: 48,
            textAlign: 'center',
            color: '#475569',
          }}>
            No digests yet. Run the AI news workflow to generate the first one.
          </div>
        ) : (
          <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
            {digests.map((digest) => (
              <DigestCard key={digest.date} digest={digest} />
            ))}
          </div>
        )}

        <div style={{ marginTop: 48, paddingTop: 24, borderTop: '1px solid rgba(255,255,255,0.06)', color: '#334155', fontSize: 13 }}>
          Generated by the AI News workflow · saved to{' '}
          <code style={{ color: '#475569', fontFamily: 'var(--font-geist-mono)' }}>personal/digests/</code>
        </div>
      </div>
    </main>
  )
}
